import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Provider } from "jotai";
import { ConfigProvider } from "antd";
export const metadata: Metadata = {
  title: "stepx-ai-web",
  description: "Generated by create next app",
};
const roboto = Poppins({
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className}`}>
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Input: {
                  paddingBlock: 10,
                  paddingInline: 12,
                  inputFontSize: 12,
                  borderRadius: 12,
                  lineHeight: 18 / 12,
                  colorText: "#101010",
                  activeBorderColor: "#FADB14",
                  colorBorder: "#F0F0F0",
                  hoverBorderColor: "#FADB14",
                  activeShadow: "0 0 0 2px rgba(250,219,20,0)",
                },
                Cascader: {
                  dropdownHeight: 260,
                  optionSelectedBg: "#F5F5F5",
                },
                Select: {
                  borderRadiusLG: 12,
                  activeBorderColor: "#FADB14",
                  hoverBorderColor: "#FADB14",
                },
                Checkbox: {
                  colorBorder: "#E5E6EB",
                  colorBgContainer: "#D0FF71",
                },
                Modal: {
                  borderRadiusLG: 16,
                },
              },
            }}
          >
            <Provider>
              <div className="w-screen h-screen">{children}</div>
            </Provider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
